### ISSUE TITLE
GCM Mode

### ISSUE THREAD

**Issue by ghost** [trustpilot/nuget-authenticated-encryption#15]
Awesome repo. Just want to find out if you're planning on adding support for the GCM mode?

**Comment by spewu** [comment]
@TachyonRSA Thanks!

I do not think there are any plans for adding GCM mode.

@irq can you confirm?

**Comment by irq** [comment]
@TachyonRSA @spewu 

No, we don't currently have plans for adding GCM mode. We are open for contributions if you or anyone else would like to build support for this.

**Comment by ghost** [comment]
@spewu @irq - I am looking add adding it to your package. Would just like to find out if you'd want the GCM mode within the Encryption class with EncryptGcm methods or should I create a new class for GCM?

Just want to check this before going ahead and creating it.

Thanks!

**Comment by irq** [comment]
@spewu Do you have some input to this? A goal of the library is to be simple to use and therefore also opinionated. Was GCM mode left out just to avoid the external dependencies like expressed in the readme or any other thoughts?

**Comment by ghost** [comment]
@irq - Just to add, if we target the project at standard 2.1 we can use the AesGcm [class built in](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=netcore-3.11)

Not sure if you're willing to target higher though.

**Comment by spewu** [comment]
> @spewu Do you have some input to this? A goal of the library is to be simple to use and therefore also opinionated. Was GCM mode left out just to avoid the external dependencies like expressed in the readme or any other thoughts?

The main reason it was left out was because we did not need it, so I saw no reason to spend time on that part. Also, back then it required adding external dependencies, and I wanted to avoid that.

Now that GCM mode is built in it makes the decision to add that support a lot easier - I would say we should go for it.

Only issue I can think of right now is that if we target netstandard 2.1, then it won't work on full framework anymore. If we still want to support full framework, then GCM mode should be added via multi target build, so that full framework would still be able to use the current functionality, and GCM mode would only be supported on .net core. I think that would be the best outcome :)

**Comment by irq** [comment]
@spewu
Thanks for the input :)

@TachyonRSA
I agree with spewu about using multi target builds.
As for where to put the code, I think it would make sense to have it in the Encryption class as the helpers are in there as well. If it seems like it gets too cluttered or confusing with the other methods in there, maybe move it to its own class.
